// Package cron assembles /etc/cron.d/iac from three declarative sources:
//
//	iac/cron.yaml                  IaC-wide jobs (e.g. drift detection)
//	services/<svc>/cron.yaml       service-scoped jobs
//	services/<svc>/backups.yaml    declarative backup specs, translated to
//	                               cron entries invoking tools/lib/backups/run.sh
//
// Entry is the canonical row of /etc/cron.d/iac; LoadCronEntries and
// LoadBackupEntries each return []Entry. Emit renders the whole crontab
// (including the standard header and per-source #-comments).
package cron

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Entry is one line of the assembled crontab (plus its description block).
// Source is populated by the loader for uniqueness + provenance reporting.
type Entry struct {
	Name        string `yaml:"name"`
	Schedule    string `yaml:"schedule"`
	Command     string `yaml:"command"`
	Log         string `yaml:"log"`
	User        string `yaml:"user,omitempty"`
	Description string `yaml:"description,omitempty"`

	Source string `yaml:"-"`
}

// Backup is the schema for one entry in services/<svc>/backups.yaml. See
// the schema header in services/coolify/backups.yaml for human docs.
type Backup struct {
	Name      string    `yaml:"name"`
	Engine    string    `yaml:"engine"`
	Host      string    `yaml:"host"`
	DestDir   string    `yaml:"dest_dir"`
	Retention Retention `yaml:"retention"`
	Schedule  string    `yaml:"schedule"`

	// postgres
	Container string `yaml:"container,omitempty"`
	User      string `yaml:"user,omitempty"`
	Database  string `yaml:"database,omitempty"`

	// sqlite
	Src string `yaml:"src,omitempty"`
}

// Retention aligns with PVE vzdump's prune-backups vocabulary. Only
// keep_last is wired today; future keep_daily / keep_weekly / keep_monthly
// plug in alongside without breaking existing YAMLs.
type Retention struct {
	KeepLast int `yaml:"keep_last"`
}

const header = `# Auto-generated by tools/lib/cmd/assemble-crons — DO NOT EDIT BY HAND.
# Sources: iac/cron.yaml, services/*/cron.yaml, services/*/backups.yaml.
# Re-run tools/apply.sh to regenerate.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

// LoadCronEntries reads iac/cron.yaml + services/*/cron.yaml in stable order.
func LoadCronEntries(root string) ([]Entry, error) {
	var files []string
	if iacCron := filepath.Join(root, "iac", "cron.yaml"); fileExists(iacCron) {
		files = append(files, iacCron)
	}
	svcFiles, err := filepath.Glob(filepath.Join(root, "services", "*", "cron.yaml"))
	if err != nil {
		return nil, fmt.Errorf("glob services/*/cron.yaml: %w", err)
	}
	sort.Strings(svcFiles)
	files = append(files, svcFiles...)

	var out []Entry
	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", rel, err)
		}
		var entries []Entry
		if err := yaml.Unmarshal(data, &entries); err != nil {
			return nil, fmt.Errorf("parse %s: %w", rel, err)
		}
		for i := range entries {
			entries[i].Source = rel
		}
		out = append(out, entries...)
	}
	return out, nil
}

// LoadBackupEntries reads services/*/backups.yaml and synthesizes one cron
// Entry per backup spec, invoking tools/lib/backups/run.sh with flags built
// from the spec.
func LoadBackupEntries(root string) ([]Entry, error) {
	files, err := filepath.Glob(filepath.Join(root, "services", "*", "backups.yaml"))
	if err != nil {
		return nil, fmt.Errorf("glob services/*/backups.yaml: %w", err)
	}
	sort.Strings(files)

	var out []Entry
	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", rel, err)
		}
		var backups []Backup
		if err := yaml.Unmarshal(data, &backups); err != nil {
			return nil, fmt.Errorf("parse %s: %w", rel, err)
		}
		for _, b := range backups {
			entry, err := backupToEntry(b, rel)
			if err != nil {
				return nil, err
			}
			out = append(out, entry)
		}
	}
	return out, nil
}

// backupToEntry validates one Backup spec and converts it into a cron
// Entry whose Command invokes tools/lib/backups/run.sh with the right flags.
func backupToEntry(b Backup, source string) (Entry, error) {
	required := map[string]string{
		"name":     b.Name,
		"engine":   b.Engine,
		"host":     b.Host,
		"dest_dir": b.DestDir,
		"schedule": b.Schedule,
	}
	for k, v := range required {
		if v == "" {
			return Entry{}, fmt.Errorf("%s: backup entry missing required field %q: %+v", source, k, b)
		}
	}
	if b.Retention.KeepLast <= 0 {
		return Entry{}, fmt.Errorf("%s: backup %q: retention.keep_last must be a positive integer (got %d)",
			source, b.Name, b.Retention.KeepLast)
	}

	args := []string{
		"--engine", b.Engine,
		"--name", b.Name,
		"--host", b.Host,
		"--dest-dir", b.DestDir,
		"--retention-keep-last", fmt.Sprintf("%d", b.Retention.KeepLast),
	}

	switch b.Engine {
	case "postgres":
		for k, v := range map[string]string{
			"container": b.Container,
			"user":      b.User,
			"database":  b.Database,
		} {
			if v == "" {
				return Entry{}, fmt.Errorf("%s: backup %q (engine=postgres) missing required field %q",
					source, b.Name, k)
			}
		}
		args = append(args,
			"--container", b.Container,
			"--user", b.User,
			"--database", b.Database,
		)
	case "sqlite":
		if b.Src == "" {
			return Entry{}, fmt.Errorf("%s: backup %q (engine=sqlite) missing required field %q",
				source, b.Name, "src")
		}
		args = append(args, "--src", b.Src)
	default:
		return Entry{}, fmt.Errorf("%s: backup %q has unknown engine %q (supported: postgres, sqlite)",
			source, b.Name, b.Engine)
	}

	return Entry{
		Name:     "backup-" + b.Name,
		Schedule: b.Schedule,
		Command:  "tools/lib/backups/run.sh " + strings.Join(args, " "),
		Log:      "/var/log/backup-" + b.Name + ".log",
		Description: fmt.Sprintf("Declarative backup (engine=%s, host=%s, retention.keep_last=%d). Spec in %s.",
			b.Engine, b.Host, b.Retention.KeepLast, source),
		Source: source,
	}, nil
}

// Emit renders the assembled crontab. Fails on duplicate names or invalid
// rows (missing required fields).
func Emit(entries []Entry) (string, error) {
	seen := map[string]string{}
	var out strings.Builder
	out.WriteString(header)

	for _, e := range entries {
		if e.Name == "" || e.Schedule == "" || e.Command == "" || e.Log == "" {
			return "", fmt.Errorf("%s: entry missing required field(s) (name/schedule/command/log): %+v", e.Source, e)
		}
		if prev, ok := seen[e.Name]; ok {
			return "", fmt.Errorf("duplicate cron name %q in %s (also in %s)", e.Name, e.Source, prev)
		}
		seen[e.Name] = e.Source

		fmt.Fprintf(&out, "\n# %s — %s\n", e.Source, e.Name)
		if desc := strings.TrimSpace(e.Description); desc != "" {
			for _, line := range strings.Split(desc, "\n") {
				if line != "" {
					fmt.Fprintf(&out, "#   %s\n", line)
				}
			}
		}
		user := e.User
		if user == "" {
			user = "root"
		}
		fmt.Fprintf(&out, "%s %s %s >> %s 2>&1\n",
			e.Schedule, user, resolveCommand(e.Command), e.Log)
	}
	return out.String(), nil
}

// resolveCommand rewrites a repo-relative path to its on-host absolute path
// (the ops LXC clones the repo at /root/homelab-iac). Absolute paths pass
// through. The path component may be followed by flags/args.
func resolveCommand(cmd string) string {
	if strings.HasPrefix(cmd, "/") {
		return cmd
	}
	if i := strings.IndexByte(cmd, ' '); i >= 0 {
		return "/root/homelab-iac/" + cmd[:i] + cmd[i:]
	}
	return "/root/homelab-iac/" + cmd
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
