package bootstrap

import (
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Emit renders the manifest to an idempotent shell script. svcDir is the
// directory of the manifest (used to resolve FileWrite.Src relative paths).
// The generated script is meant to be ssh-piped into `sh -s` on the target
// LXC; it sets `set -e` and `export DEBIAN_FRONTEND=noninteractive` itself.
func Emit(m Manifest, svcDir string) (string, error) {
	var b builder
	b.printf("# Auto-generated by tools/lib/cmd/bootstrap from a bootstrap.yaml — DO NOT EDIT BY HAND.\n")
	b.printf("set -e\nexport DEBIAN_FRONTEND=noninteractive\n\n")

	// Run `apt-get update` once if anything needs apt.
	needsAptUpdate := len(m.APT.Repos) > 0 || len(m.APT.Packages) > 0
	if needsAptUpdate {
		b.section("apt prerequisites")
		b.printf("apt-get update -qq\n")
		// Install gnupg+curl+ca-certificates first if we'll add custom repos
		// (the gpg dearmor step needs them). Idempotent — apt is fine to
		// re-install present packages.
		if len(m.APT.Repos) > 0 {
			b.printf("apt-get install -y -qq curl ca-certificates gnupg\n")
		}
	}

	if len(m.APT.Repos) > 0 {
		b.section("apt repos")
		for _, r := range m.APT.Repos {
			b.aptRepo(r)
		}
		b.printf("apt-get update -qq\n")
	}

	if len(m.APT.Packages) > 0 {
		b.section("apt packages")
		b.printf("apt-get install -y -qq %s\n", shJoin(m.APT.Packages))
	}

	for _, bin := range m.Binary {
		b.section(fmt.Sprintf("binary: %s", bin.Name))
		b.binary(bin)
	}

	for _, g := range m.Groups {
		b.section(fmt.Sprintf("group: %s", g.Name))
		b.group(g)
	}

	for _, u := range m.Users {
		b.section(fmt.Sprintf("user: %s", u.Name))
		b.user(u)
	}

	for _, d := range m.Dirs {
		b.dir(d)
	}

	for _, f := range m.Files {
		b.section(fmt.Sprintf("file: %s", f.Dest))
		if err := b.file(f, svcDir); err != nil {
			return "", fmt.Errorf("file %s: %w", f.Dest, err)
		}
	}

	for _, s := range m.Secrets {
		b.section(fmt.Sprintf("random secrets: %s", s.Dest))
		b.secrets(s)
	}

	for i, c := range m.Cmds {
		b.section(fmt.Sprintf("command #%d", i+1))
		b.command(c)
	}

	if m.Systemd.DaemonReload || len(m.Systemd.Enable) > 0 || len(m.Systemd.Start) > 0 {
		b.section("systemd")
		if m.Systemd.DaemonReload {
			b.printf("systemctl daemon-reload\n")
		}
		for _, u := range m.Systemd.Enable {
			b.printf("systemctl enable --quiet %s 2>/dev/null || true\n", u)
		}
		for _, u := range m.Systemd.Start {
			b.printf("systemctl restart %s\n", u)
			b.printf("systemctl is-active --quiet %s\n", u)
		}
	}

	return b.s.String(), nil
}

// builder accumulates the generated shell.
type builder struct {
	s strings.Builder
}

func (b *builder) printf(format string, args ...any) {
	fmt.Fprintf(&b.s, format, args...)
}

func (b *builder) section(title string) {
	b.printf("\n# ── %s ─────────────────────────────────────────\n", title)
}

func (b *builder) aptRepo(r APTRepo) {
	// Dearmor only if keyring missing (avoid re-curling on every run).
	b.printf("install -d -m 0755 /usr/share/keyrings\n")
	b.printf("if [ ! -s '%s' ]; then\n", r.KeyringDest)
	b.printf("  curl -fsSL '%s' | gpg --dearmor -o '%s'\n", r.KeyringURL, r.KeyringDest)
	b.printf("fi\n")
	listPath := fmt.Sprintf("/etc/apt/sources.list.d/%s.list", r.Name)
	b.printf("if [ ! -s '%s' ]; then\n", listPath)
	b.printf("  printf '%%s\\n' %s > '%s'\n", shQuote(r.DebLine), listPath)
	b.printf("fi\n")
}

func (b *builder) binary(bin Binary) {
	mode := bin.Mode
	if mode == "" {
		mode = "0755"
	}
	b.printf("if [ ! -x '%s' ]; then\n", bin.Dest)
	b.printf("  _tag=$(curl -fsSL 'https://api.github.com/repos/%s/releases/latest' | jq -r .tag_name)\n", bin.GithubRepo)
	b.printf("  _tag_num=${_tag#v}\n")
	asset := strings.ReplaceAll(bin.AssetTemplate, "{tag_num}", "${_tag_num}")
	asset = strings.ReplaceAll(asset, "{tag}", "${_tag}")
	url := fmt.Sprintf("https://github.com/%s/releases/download/${_tag}/%s", bin.GithubRepo, asset)
	b.printf("  curl -fsSL \"%s\" -o /tmp/%s.dl\n", url, bin.Name)
	if bin.Extract != "" {
		b.printf("  tar -xzf /tmp/%s.dl -C /tmp '%s'\n", bin.Name, bin.Extract)
		b.printf("  install -m %s '/tmp/%s' '%s'\n", mode, bin.Extract, bin.Dest)
		b.printf("  rm -f '/tmp/%s.dl' '/tmp/%s'\n", bin.Name, bin.Extract)
	} else {
		b.printf("  install -m %s '/tmp/%s.dl' '%s'\n", mode, bin.Name, bin.Dest)
		b.printf("  rm -f '/tmp/%s.dl'\n", bin.Name)
	}
	b.printf("fi\n")
}

func (b *builder) group(g Group) {
	// Pinned GID when set — required for shared-group GIDs that must match
	// host-side ACLs across unprivileged LXCs. Without a GID, useradd-time
	// allocation in the system range is fine.
	if g.GID > 0 {
		b.printf("getent group %s >/dev/null 2>&1 || groupadd --gid %d %s\n", g.Name, g.GID, g.Name)
	} else {
		b.printf("getent group %s >/dev/null 2>&1 || groupadd --system %s\n", g.Name, g.Name)
	}
}

func (b *builder) user(u User) {
	b.printf("id %s >/dev/null 2>&1 || useradd ", u.Name)
	var flags []string
	if u.System {
		flags = append(flags, "--system")
	}
	if u.NoCreateHome {
		flags = append(flags, "--no-create-home")
	}
	if u.Shell != "" {
		flags = append(flags, fmt.Sprintf("--shell '%s'", u.Shell))
	}
	if u.Home != "" {
		flags = append(flags, fmt.Sprintf("--home-dir '%s'", u.Home))
	}
	b.printf("%s %s\n", strings.Join(flags, " "), u.Name)
	// Idempotent — usermod -aG with an already-member group is a no-op.
	if len(u.ExtraGroups) > 0 {
		b.printf("usermod -aG %s %s\n", strings.Join(u.ExtraGroups, ","), u.Name)
	}
}

func (b *builder) dir(d Dir) {
	flags := []string{"-d"}
	if d.Owner != "" {
		owner := strings.SplitN(d.Owner, ":", 2)
		flags = append(flags, fmt.Sprintf("-o '%s'", owner[0]))
		if len(owner) > 1 {
			flags = append(flags, fmt.Sprintf("-g '%s'", owner[1]))
		}
	}
	if d.Mode != "" {
		flags = append(flags, "-m "+d.Mode)
	}
	b.printf("install %s '%s'\n", strings.Join(flags, " "), d.Path)
}

func (b *builder) file(f FileWrite, svcDir string) error {
	mode := f.Mode
	if mode == "" {
		mode = "0644"
	}
	// Stage to a tmp file, swap into place only on change to keep
	// daemon-reload triggers honest. base64-decode inline keeps the script
	// self-contained (no extra scp).
	var contentExpr string
	switch {
	case f.Content != "":
		contentExpr = literalBase64Decode(f.Content)
	case f.ContentFromEnv != "":
		// The env var must be set in the ssh environment; the apply.sh caller
		// uses "VAR=val sh -s" so it lands in env.
		contentExpr = fmt.Sprintf("printf '%%s\\n' \"$%s\"", f.ContentFromEnv)
	case f.Src != "":
		fullPath := filepath.Join(svcDir, f.Src)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			return err
		}
		contentExpr = literalBase64Decode(string(data))
	}

	tmp := "/tmp/.bs-" + filepath.Base(f.Dest)
	b.printf("install -d -m 0755 '%s'\n", filepath.Dir(f.Dest))
	b.printf("%s > '%s'\n", contentExpr, tmp)
	b.printf("if ! cmp -s '%s' '%s' 2>/dev/null; then\n", tmp, f.Dest)
	b.printf("  install -m %s '%s' '%s'\n", mode, tmp, f.Dest)
	if f.Owner != "" {
		b.printf("  chown '%s' '%s'\n", f.Owner, f.Dest)
	}
	// .service files put under /etc/systemd/system need a daemon-reload.
	if strings.HasPrefix(f.Dest, "/etc/systemd/system/") && strings.HasSuffix(f.Dest, ".service") {
		b.printf("  systemctl daemon-reload\n")
	}
	if f.RestartOnChange != "" {
		b.printf("  systemctl restart %s\n", f.RestartOnChange)
	}
	b.printf("fi\n")
	b.printf("rm -f '%s'\n", tmp)
	return nil
}

func (b *builder) secrets(s SecretsFile) {
	mode := s.Mode
	if mode == "" {
		mode = "0600"
	}
	guard := ""
	if s.IfMissing {
		guard = fmt.Sprintf("if [ ! -s '%s' ]; then", s.Dest)
	} else {
		guard = "if true; then"
	}
	b.printf("install -d -m 0755 '%s'\n", filepath.Dir(s.Dest))
	b.printf("%s\n", guard)
	b.printf("  {\n")
	for _, e := range s.Entries {
		// alphanumeric of requested length, from /dev/urandom. tr filters out
		// non-alnum so we always get exactly `length` chars.
		b.printf("    printf '%%s=%%s\\n' '%s' \"$(tr -dc A-Za-z0-9 </dev/urandom | head -c %d)\"\n", e.Key, e.Length)
	}
	b.printf("  } > '%s'\n", s.Dest)
	b.printf("  chmod %s '%s'\n", mode, s.Dest)
	if s.Owner != "" {
		b.printf("  chown '%s' '%s'\n", s.Owner, s.Dest)
	}
	b.printf("fi\n")
}

func (b *builder) command(c Command) {
	guards := []string{}
	if c.IfMissingFile != "" {
		guards = append(guards, fmt.Sprintf("[ ! -e '%s' ]", c.IfMissingFile))
	}
	if c.IfMissingCmd != "" {
		guards = append(guards, fmt.Sprintf("! command -v %s >/dev/null", c.IfMissingCmd))
	}
	if len(guards) > 0 {
		b.printf("if %s; then\n", strings.Join(guards, " && "))
		// Indent the user shell by 2 spaces.
		for _, line := range strings.Split(strings.TrimRight(c.Shell, "\n"), "\n") {
			b.printf("  %s\n", line)
		}
		b.printf("fi\n")
	} else {
		b.printf("%s\n", strings.TrimRight(c.Shell, "\n"))
	}
}

// literalBase64Decode returns a shell expression that produces the literal
// content on stdout via `printf '%s' <base64> | base64 -d`. Safer than
// embedding raw heredocs (which can collide with content delimiters).
func literalBase64Decode(content string) string {
	enc := base64.StdEncoding.EncodeToString([]byte(content))
	return fmt.Sprintf("printf '%%s' '%s' | base64 -d", enc)
}

// shJoin space-joins args for safe inclusion in a shell command line; each
// arg gets single-quoted. (Used for `apt-get install <packages>`.)
func shJoin(args []string) string {
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = shQuote(a)
	}
	return strings.Join(quoted, " ")
}

// shQuote single-quotes a string for shell, escaping any embedded single
// quotes via the standard '\''-glue pattern.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// silence "unused" on io until we add streaming writes
var _ = io.EOF
