#!/bin/sh
# Seed all secrets needed by iedora-iac into Bitwarden Secrets Manager.
#
# Idempotent: each secret is created only if missing. Re-running this is safe
# and reports which ones already existed.
#
# Pre-reqs:
#   - bws CLI installed
#   - BWS_ACCESS_TOKEN exported (or /root/.bws-token present)
#   - BW_ORGANIZATION_ID exported OR available in iac/.envrc
#   - A BWS project named "homelab" already exists
#
# Inputs (prompted): CF API token, PVE API token, admin name/email, ntfy topic.
# Auto-generated: TOFU_STATE_PASSPHRASE, IEDORA_ADMIN_PASSWORD, NTFY_TOPIC.

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=${SCRIPT_DIR%/tools}
if [ -f "$REPO_ROOT/iac/.envrc" ]; then
  # shellcheck disable=SC1091
  . "$REPO_ROOT/iac/.envrc" >/dev/null 2>&1 || true
fi

command -v bws >/dev/null || { echo "ERROR: bws CLI not found in PATH"; exit 1; }
[ -n "${BWS_ACCESS_TOKEN:-${BW_ACCESS_TOKEN:-}}" ] || { echo "ERROR: BWS_ACCESS_TOKEN not set"; exit 1; }

PROJECT_NAME=${BWS_PROJECT_NAME:-homelab}
PROJECT_ID=$(bws project list --output json | jq -r --arg n "$PROJECT_NAME" '.[] | select(.name==$n) | .id')
[ -n "$PROJECT_ID" ] && [ "$PROJECT_ID" != "null" ] || {
  echo "ERROR: BWS project '$PROJECT_NAME' not found. Create it first via the BWS web UI."
  exit 1
}

# Cache the full secret list once (saves N API calls).
SECRETS_JSON=$(bws secret list --output json)

bws_has() {
  echo "$SECRETS_JSON" | jq -e --arg k "$1" 'any(.[]; .key==$k)' >/dev/null
}

bws_create() {
  # args: key value note
  bws secret create "$1" "$2" "$PROJECT_ID" --note "$3" >/dev/null
  # refresh cache so next bws_has sees it
  SECRETS_JSON=$(bws secret list --output json)
}

rand24() { openssl rand -base64 24 | tr -d '/+='; }
rand40() { openssl rand -hex 20; }

prompt() {
  # args: varname prompt-text
  printf '%s: ' "$2" >&2
  read -r _val
  eval "$1=\$_val"
}

prompt_secret() {
  printf '%s: ' "$2" >&2
  stty -echo
  read -r _val
  stty echo
  printf '\n' >&2
  eval "$1=\$_val"
}

echo "==> BWS project: $PROJECT_NAME ($PROJECT_ID)"
echo "==> existing secrets: $(echo "$SECRETS_JSON" | jq -r 'map(.key) | join(", ")')"
echo

# --- TOFU_STATE_PASSPHRASE ---
if bws_has TOFU_STATE_PASSPHRASE; then
  echo "[skip] TOFU_STATE_PASSPHRASE"
else
  V=$(rand24)
  bws_create TOFU_STATE_PASSPHRASE "$V" "OpenTofu state encryption passphrase (PBKDF2-AES-GCM). Auto-generated by seed-bws.sh."
  echo "[new]  TOFU_STATE_PASSPHRASE (24-byte random)"
fi

# --- CLOUDFLARE_API_TOKEN ---
if bws_has CLOUDFLARE_API_TOKEN; then
  echo "[skip] CLOUDFLARE_API_TOKEN"
else
  echo
  echo "Need a Cloudflare API token with these permissions on the iedora.com zone:"
  echo "  - Account / Cloudflare Tunnel: Edit"
  echo "  - Account / Zero Trust: Edit"
  echo "  - Zone / DNS: Edit"
  echo "Create at: https://dash.cloudflare.com/profile/api-tokens"
  prompt_secret CF_TOKEN "  Paste CF API token"
  bws_create CLOUDFLARE_API_TOKEN "$CF_TOKEN" "Cloudflare API token for tunnel + DNS + Zero Trust on iedora.com."
  echo "[new]  CLOUDFLARE_API_TOKEN"
fi

# --- PVE_API_TOKEN ---
if bws_has PVE_API_TOKEN; then
  echo "[skip] PVE_API_TOKEN"
else
  echo
  echo "On the PVE host, run:"
  echo "  pveum user token add root@pam tofu --privsep=0"
  echo "It prints a JSON-ish object with a 'value' field; the full token is:"
  echo "  root@pam!tofu=<value>"
  prompt_secret PVE_TOKEN "  Paste the full PVE token (format root@pam!tofu=<uuid>)"
  bws_create PVE_API_TOKEN "$PVE_TOKEN" "PVE API token for bpg/proxmox provider. Format: root@pam!tofu=<uuid>."
  echo "[new]  PVE_API_TOKEN"
fi

# --- IEDORA_ADMIN_NAME ---
if bws_has IEDORA_ADMIN_NAME; then
  echo "[skip] IEDORA_ADMIN_NAME"
else
  prompt ADMIN_NAME "Admin display name (e.g. Eduardo)"
  bws_create IEDORA_ADMIN_NAME "$ADMIN_NAME" "Display name used by Coolify + Authelia bootstrap. Shared."
  echo "[new]  IEDORA_ADMIN_NAME"
fi

# --- IEDORA_ADMIN_EMAIL ---
if bws_has IEDORA_ADMIN_EMAIL; then
  echo "[skip] IEDORA_ADMIN_EMAIL"
else
  prompt ADMIN_EMAIL "Admin email (used as Coolify + Authelia login)"
  bws_create IEDORA_ADMIN_EMAIL "$ADMIN_EMAIL" "Login email for Coolify + Authelia. Shared."
  echo "[new]  IEDORA_ADMIN_EMAIL"
fi

# --- IEDORA_ADMIN_PASSWORD ---
if bws_has IEDORA_ADMIN_PASSWORD; then
  echo "[skip] IEDORA_ADMIN_PASSWORD"
else
  V=$(rand24)
  bws_create IEDORA_ADMIN_PASSWORD "$V" "Admin password for Coolify + Authelia (shared). Auto-generated by seed-bws.sh — change via the respective UIs after first login if you want a memorable one."
  echo "[new]  IEDORA_ADMIN_PASSWORD (24-byte random — fetch with: bws secret list | jq '.[] | select(.key==\"IEDORA_ADMIN_PASSWORD\") | .value')"
fi

# --- NTFY_TOPIC ---
if bws_has NTFY_TOPIC; then
  echo "[skip] NTFY_TOPIC"
else
  # ntfy topics are publicly addressable strings — they ARE the secret.
  # Generate a long random one so it's unguessable.
  V="iedora-drift-$(rand40 | head -c 16)"
  bws_create NTFY_TOPIC "$V" "ntfy.sh topic for IaC drift alerts. Subscribe in the ntfy app to: https://ntfy.sh/$V"
  echo "[new]  NTFY_TOPIC = $V"
  echo "       → Subscribe in the ntfy mobile app or browser at https://ntfy.sh/$V"
fi

echo
echo "==> seed complete."
echo "    Re-run safely; existing secrets are never overwritten."
echo "    To view a value: bws secret list | jq -r '.[] | select(.key==\"<KEY>\") | .value'"
