#!/bin/sh
# Seed all secrets needed by iedora-iac into Bitwarden Secrets Manager.
#
# Idempotent: each secret is created only if missing. Re-running this is safe
# and reports which ones already existed.
#
# Pre-reqs:
#   - bws CLI installed
#   - BWS_ACCESS_TOKEN exported (or /root/.bws-token present)
#   - BW_ORGANIZATION_ID exported OR available in iac/.envrc
#   - A BWS project named "homelab" already exists
#
# Inputs (prompted): CF API token, PVE API token, admin name/email, ntfy topic.
# Auto-generated: TOFU_STATE_PASSPHRASE, IEDORA_ADMIN_PASSWORD, NTFY_TOPIC.

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=${SCRIPT_DIR%/tools}
if [ -f "$REPO_ROOT/iac/.envrc" ]; then
  # shellcheck disable=SC1091
  . "$REPO_ROOT/iac/.envrc" >/dev/null 2>&1 || true
fi

command -v bws >/dev/null || { echo "ERROR: bws CLI not found in PATH"; exit 1; }
[ -n "${BWS_ACCESS_TOKEN:-${BW_ACCESS_TOKEN:-}}" ] || { echo "ERROR: BWS_ACCESS_TOKEN not set"; exit 1; }

PROJECT_NAME=${BWS_PROJECT_NAME:-homelab}
PROJECT_ID=$(bws project list --output json | jq -r --arg n "$PROJECT_NAME" '.[] | select(.name==$n) | .id')
[ -n "$PROJECT_ID" ] && [ "$PROJECT_ID" != "null" ] || {
  echo "ERROR: BWS project '$PROJECT_NAME' not found. Create it first via the BWS web UI."
  exit 1
}

# Cache the full secret list once (saves N API calls).
SECRETS_JSON=$(bws secret list --output json)

bws_has() {
  echo "$SECRETS_JSON" | jq -e --arg k "$1" 'any(.[]; .key==$k)' >/dev/null
}

bws_create() {
  # args: key value note
  bws secret create "$1" "$2" "$PROJECT_ID" --note "$3" >/dev/null
  # refresh cache so next bws_has sees it
  SECRETS_JSON=$(bws secret list --output json)
}

rand24() { openssl rand -base64 24 | tr -d '/+='; }
rand40() { openssl rand -hex 20; }

prompt() {
  # args: varname prompt-text
  printf '%s: ' "$2" >&2
  read -r _val
  eval "$1=\$_val"
}

prompt_secret() {
  printf '%s: ' "$2" >&2
  stty -echo
  read -r _val
  stty echo
  printf '\n' >&2
  eval "$1=\$_val"
}

echo "==> BWS project: $PROJECT_NAME ($PROJECT_ID)"
echo "==> existing secrets: $(echo "$SECRETS_JSON" | jq -r 'map(.key) | join(", ")')"
echo

# --- TOFU_STATE_PASSPHRASE ---
if bws_has TOFU_STATE_PASSPHRASE; then
  echo "[skip] TOFU_STATE_PASSPHRASE"
else
  V=$(rand24)
  bws_create TOFU_STATE_PASSPHRASE "$V" "OpenTofu state encryption passphrase (PBKDF2-AES-GCM). Auto-generated by seed-bws.sh."
  echo "[new]  TOFU_STATE_PASSPHRASE (24-byte random)"
fi

# --- CLOUDFLARE_API_TOKEN ---
if bws_has CLOUDFLARE_API_TOKEN; then
  echo "[skip] CLOUDFLARE_API_TOKEN"
else
  echo
  echo "Need a Cloudflare API token with these permissions on the iedora.com zone:"
  echo "  - Account / Cloudflare Tunnel: Edit"
  echo "  - Account / Zero Trust: Edit"
  echo "  - Account / Cloudflare R2: Edit         (for the tofu state bucket)"
  echo "  - User    / API Tokens: Edit            (to mint the scoped R2 token)"
  echo "  - Zone    / DNS: Edit"
  echo "Create at: https://dash.cloudflare.com/profile/api-tokens"
  prompt_secret CF_TOKEN "  Paste CF API token"
  bws_create CLOUDFLARE_API_TOKEN "$CF_TOKEN" "Cloudflare API token for tunnel + DNS + Zero Trust on iedora.com."
  echo "[new]  CLOUDFLARE_API_TOKEN"
fi

# --- PVE_ROOT_PASSWORD ---
# We use root@pam password (not an API token) because PVE has a hardcoded
# restriction: tokens cannot change non-nesting LXC feature flags (keyctl).
# Coolify + runner LXCs need keyctl=1 for Docker. privsep=0 tokens were already
# root-equivalent, so this is the same security posture.
if bws_has PVE_ROOT_PASSWORD; then
  echo "[skip] PVE_ROOT_PASSWORD"
else
  echo
  echo "Need the PVE root@pam password (set during PVE install)."
  prompt_secret PVE_PASS "  PVE root password"
  bws_create PVE_ROOT_PASSWORD "$PVE_PASS" "PVE root@pam password for bpg/proxmox provider. Required because API tokens cannot set keyctl on LXCs (PVE hardcoded restriction)."
  echo "[new]  PVE_ROOT_PASSWORD"
fi

# --- IEDORA_ADMIN_NAME ---
if bws_has IEDORA_ADMIN_NAME; then
  echo "[skip] IEDORA_ADMIN_NAME"
else
  prompt ADMIN_NAME "Admin display name (e.g. Eduardo)"
  bws_create IEDORA_ADMIN_NAME "$ADMIN_NAME" "Display name used by Coolify + Authelia bootstrap. Shared."
  echo "[new]  IEDORA_ADMIN_NAME"
fi

# --- IEDORA_ADMIN_EMAIL ---
if bws_has IEDORA_ADMIN_EMAIL; then
  echo "[skip] IEDORA_ADMIN_EMAIL"
else
  prompt ADMIN_EMAIL "Admin email (used as Coolify + Authelia login)"
  bws_create IEDORA_ADMIN_EMAIL "$ADMIN_EMAIL" "Login email for Coolify + Authelia. Shared."
  echo "[new]  IEDORA_ADMIN_EMAIL"
fi

# --- IEDORA_ADMIN_PASSWORD ---
if bws_has IEDORA_ADMIN_PASSWORD; then
  echo "[skip] IEDORA_ADMIN_PASSWORD"
else
  V=$(rand24)
  bws_create IEDORA_ADMIN_PASSWORD "$V" "Admin password for Coolify + Authelia (shared). Auto-generated by seed-bws.sh — change via the respective UIs after first login if you want a memorable one."
  echo "[new]  IEDORA_ADMIN_PASSWORD (24-byte random — fetch with: bws secret list | jq '.[] | select(.key==\"IEDORA_ADMIN_PASSWORD\") | .value')"
fi

# --- NTFY_TOPIC ---
if bws_has NTFY_TOPIC; then
  echo "[skip] NTFY_TOPIC"
else
  # ntfy topics are publicly addressable strings — they ARE the secret.
  # Generate a long random one so it's unguessable.
  V="iedora-drift-$(rand40 | head -c 16)"
  bws_create NTFY_TOPIC "$V" "ntfy.sh topic for IaC drift alerts. Subscribe in the ntfy app to: https://ntfy.sh/$V"
  echo "[new]  NTFY_TOPIC = $V"
  echo "       → Subscribe in the ntfy mobile app or browser at https://ntfy.sh/$V"
fi

# ─── R2 backend for tofu state ────────────────────────────────────────────────
# Stores both stacks' state in a Cloudflare R2 bucket. Native S3 locking
# (OpenTofu 1.10+ use_lockfile) — no DynamoDB. State stays cifrado pelo
# encryption{} block (TOFU_STATE_PASSPHRASE) — defense in depth.
#
# Requires the existing CLOUDFLARE_API_TOKEN to have these extra scopes:
#   - Account / Cloudflare R2:Edit
#   - User / API Tokens:Edit  (to create the scoped R2 token below)
# If the scopes are missing, the calls return 403 and we print clear guidance.

R2_BUCKET=${R2_BUCKET:-iedora-iac-state}
R2_LOCATION=${R2_LOCATION:-weur}   # closest to PT — change for other regions

cf_api() {
  # args: METHOD PATH [json-body]
  _m=$1; _p=$2; _b=${3:-}
  if [ -n "$_b" ]; then
    curl -sS -X "$_m" \
      -H "Authorization: Bearer $CF_TOKEN" \
      -H "Content-Type: application/json" \
      --data "$_b" \
      "https://api.cloudflare.com/client/v4$_p"
  else
    curl -sS -X "$_m" \
      -H "Authorization: Bearer $CF_TOKEN" \
      "https://api.cloudflare.com/client/v4$_p"
  fi
}

if bws_has R2_ACCESS_KEY_ID && bws_has R2_SECRET_ACCESS_KEY && bws_has R2_ACCOUNT_ID; then
  echo "[skip] R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY / R2_ACCOUNT_ID"
else
  echo
  echo "==> bootstrapping Cloudflare R2 for tofu state…"
  CF_TOKEN=$(echo "$SECRETS_JSON" | jq -r '.[] | select(.key=="CLOUDFLARE_API_TOKEN") | .value')
  [ -n "$CF_TOKEN" ] && [ "$CF_TOKEN" != "null" ] || { echo "ERROR: CLOUDFLARE_API_TOKEN missing in BWS — seed it first"; exit 1; }

  # 1. Find account ID via the zones endpoint (reuses the existing token's scope).
  ACCOUNT_ID=$(cf_api GET '/zones?per_page=1' | jq -r '.result[0].account.id // empty')
  [ -n "$ACCOUNT_ID" ] || { echo "ERROR: failed to fetch account_id — token may be missing Zone:Read"; exit 1; }
  echo "    account_id = $ACCOUNT_ID"

  # 2. Create the bucket (idempotent — 409 means it exists, both are fine).
  BUCKET_RESP=$(cf_api POST "/accounts/$ACCOUNT_ID/r2/buckets" \
    "{\"name\":\"$R2_BUCKET\",\"locationHint\":\"$R2_LOCATION\",\"storageClass\":\"Standard\"}")
  if echo "$BUCKET_RESP" | jq -e '.success == true' >/dev/null; then
    echo "    bucket $R2_BUCKET created in $R2_LOCATION"
  elif echo "$BUCKET_RESP" | jq -e '[.errors[].code] | contains([10004])' >/dev/null 2>&1; then
    echo "    bucket $R2_BUCKET already exists — reusing"
  else
    echo "ERROR: failed to create bucket: $BUCKET_RESP" >&2
    echo "       (does CLOUDFLARE_API_TOKEN have 'Account / Cloudflare R2: Edit' scope?)" >&2
    exit 1
  fi

  # 3. Create a bucket-scoped R2 API token (Object Read & Write). We use the
  #    R2 temp-credentials endpoint with a permanent grant; this returns the
  #    AWS-compatible accessKeyId + secretAccessKey directly (no SHA256 dance).
  TOKEN_BODY=$(jq -nc --arg b "$R2_BUCKET" '{
    name: ("iedora-iac-tofu-state-" + (now | tostring | split(".")[0])),
    policies: [{
      permission_groups: [
        {id: "2efd5506f9c8494dacb1fa10a3e7d5b6", name: "Workers R2 Storage Bucket Item Write"}
      ],
      resources: { ("com.cloudflare.api.account.r2.bucket." + $b): "*" }
    }]
  }')
  TOKEN_RESP=$(cf_api POST '/user/tokens' "$TOKEN_BODY")
  KEY_ID=$(echo "$TOKEN_RESP" | jq -r '.result.id // empty')
  KEY_VAL=$(echo "$TOKEN_RESP" | jq -r '.result.value // empty')
  if [ -z "$KEY_ID" ] || [ -z "$KEY_VAL" ]; then
    echo "ERROR: failed to mint R2 API token: $TOKEN_RESP" >&2
    echo "       (does CLOUDFLARE_API_TOKEN have 'User / API Tokens: Edit' scope?)" >&2
    exit 1
  fi
  # R2 convention: Access Key ID = token ID, Secret = SHA-256 of the token value.
  SECRET=$(printf '%s' "$KEY_VAL" | sha256sum | cut -d' ' -f1)

  bws_create R2_ACCESS_KEY_ID "$KEY_ID" "R2 access key ID for tofu state backend (bucket-scoped). Minted by seed-bws.sh."
  bws_create R2_SECRET_ACCESS_KEY "$SECRET" "R2 secret access key (= SHA-256 of the bucket-scoped Cloudflare API token value)."
  bws_create R2_ACCOUNT_ID "$ACCOUNT_ID" "Cloudflare account ID — used to build the R2 S3 endpoint URL (https://\$ACCOUNT_ID.r2.cloudflarestorage.com)."
  echo "[new]  R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY / R2_ACCOUNT_ID"
fi

echo
echo "==> seed complete."
echo "    Re-run safely; existing secrets are never overwritten."
echo "    To view a value: bws secret list | jq -r '.[] | select(.key==\"<KEY>\") | .value'"
