// Command assemble-crons emits a single /etc/cron.d/iac crontab assembled
// from every services/*/cron.yaml in the repo.
//
// Each service that needs periodic jobs declares them in its own
// services/<svc>/cron.yaml (list of entries). This binary reads them all,
// validates required fields, and prints the full crontab to stdout. The
// caller (tools/apply.sh phase 8) installs it with copy-if-different.
//
// Schema (per entry):
//
//	name:        unique identifier (must be unique across all services)
//	schedule:    crontab time spec (e.g. "0 4 */25 * *")
//	command:     path to executable; repo-relative is rewritten to absolute
//	             /root/iedora-iac/<command>
//	log:         absolute path to log file
//	user:        optional, defaults to "root"
//	description: optional, free-form (becomes #-comments above the line)
//
// Usage:
//
//	go run ./tools/lib/assemble-crons [<repo-root>]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type Entry struct {
	Name        string `yaml:"name"`
	Schedule    string `yaml:"schedule"`
	Command     string `yaml:"command"`
	Log         string `yaml:"log"`
	User        string `yaml:"user,omitempty"`
	Description string `yaml:"description,omitempty"`
}

const header = `# Auto-generated by tools/lib/assemble-crons — DO NOT EDIT BY HAND.
# Source of truth: services/*/cron.yaml. Re-run tools/apply.sh to regenerate.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

func main() {
	repo := "."
	if len(os.Args) > 1 {
		repo = os.Args[1]
	}
	root, err := filepath.Abs(repo)
	if err != nil {
		fatalf("resolve repo root: %v", err)
	}

	pattern := filepath.Join(root, "services", "*", "cron.yaml")
	files, err := filepath.Glob(pattern)
	if err != nil {
		fatalf("glob %s: %v", pattern, err)
	}
	sort.Strings(files)

	seen := map[string]string{} // name -> source path (for uniqueness check)
	var out strings.Builder
	out.WriteString(header)

	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			fatalf("read %s: %v", rel, err)
		}
		var entries []Entry
		if err := yaml.Unmarshal(data, &entries); err != nil {
			fatalf("parse %s: %v", rel, err)
		}
		for _, e := range entries {
			if e.Name == "" || e.Schedule == "" || e.Command == "" || e.Log == "" {
				fatalf("%s: entry missing required field(s) (need name/schedule/command/log): %+v", rel, e)
			}
			if prev, ok := seen[e.Name]; ok {
				fatalf("duplicate cron name %q in %s (also in %s)", e.Name, rel, prev)
			}
			seen[e.Name] = rel

			fmt.Fprintf(&out, "\n# %s — %s\n", rel, e.Name)
			if desc := strings.TrimSpace(e.Description); desc != "" {
				for _, line := range strings.Split(desc, "\n") {
					if line != "" {
						fmt.Fprintf(&out, "#   %s\n", line)
					}
				}
			}
			user := e.User
			if user == "" {
				user = "root"
			}
			fmt.Fprintf(&out, "%s %s %s >> %s 2>&1\n",
				e.Schedule, user, resolveCommand(e.Command), e.Log)
		}
	}

	if _, err := os.Stdout.WriteString(out.String()); err != nil {
		fatalf("write stdout: %v", err)
	}
}

// resolveCommand rewrites a repo-relative path to its on-host absolute path
// (the ops LXC clones the repo at /root/iedora-iac). Absolute paths pass through.
func resolveCommand(cmd string) string {
	if strings.HasPrefix(cmd, "/") {
		return cmd
	}
	return "/root/iedora-iac/" + cmd
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "assemble-crons: "+format+"\n", args...)
	os.Exit(1)
}
