// Command assemble-crons emits a single /etc/cron.d/iac crontab assembled
// from three well-known per-source locations:
//
//   - iac/cron.yaml              IaC-wide jobs (e.g. drift detection)
//   - services/<svc>/cron.yaml   service-scoped jobs (e.g. token rotation)
//   - services/<svc>/backups.yaml declarative backup specs, translated to
//                                 cron entries invoking tools/lib/backups/run.sh
//
// The split mirrors ownership: a cron whose purpose is maintaining a single
// service lives with that service; a cron about the IaC system as a whole
// (spans stacks, doesn't belong to any one service) lives in iac/. Backup
// schedules + retention live in backups.yaml so adding a new backup is a
// YAML edit, not a new shell script.
//
// This binary reads all of them, validates required fields, dedups names,
// and prints the full crontab to stdout. The caller (tools/apply.sh
// phase 8) installs it with copy-if-different.
//
// Cron schema (per entry in cron.yaml):
//
//	name:        unique identifier (must be unique across all sources)
//	schedule:    crontab time spec (e.g. "0 4 */25 * *")
//	command:     path to executable; repo-relative is rewritten to absolute
//	             /root/homelab-iac/<command>
//	log:         absolute path to log file
//	user:        optional, defaults to "root"
//	description: optional, free-form (becomes #-comments above the line)
//
// Backup schema (per entry in services/<svc>/backups.yaml):
//
//	name       unique identifier (also forms log filename + dump file prefix)
//	engine     postgres | sqlite
//	host       service name (resolved at run-time by ip_of from network/ips.yaml)
//	dest_dir   absolute path on the target host where dumps land
//	retention  nested block — keep_last: <int>  (only dimension wired today)
//	           Vocabulary aligns with PVE vzdump's prune-backups (keep_last,
//	           future keep_daily, keep_weekly, keep_monthly).
//	schedule   cron expression (5 fields, UTC)
//
//	postgres-specific: container, user, database
//	sqlite-specific:   src
//
// Usage:
//
//	go run ./tools/lib/assemble-crons [<repo-root>]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type Entry struct {
	Name        string `yaml:"name"`
	Schedule    string `yaml:"schedule"`
	Command     string `yaml:"command"`
	Log         string `yaml:"log"`
	User        string `yaml:"user,omitempty"`
	Description string `yaml:"description,omitempty"`

	// Source tracking — set by the loader, not present in YAML.
	source string
}

type Backup struct {
	Name      string    `yaml:"name"`
	Engine    string    `yaml:"engine"`
	Host      string    `yaml:"host"`
	DestDir   string    `yaml:"dest_dir"`
	Retention Retention `yaml:"retention"`
	Schedule  string    `yaml:"schedule"`

	// postgres
	Container string `yaml:"container,omitempty"`
	User      string `yaml:"user,omitempty"`
	Database  string `yaml:"database,omitempty"`

	// sqlite
	Src string `yaml:"src,omitempty"`
}

// Retention is a nested block on each backup entry. Vocabulary aligns
// with PVE vzdump's prune-backups: keep_last (count), future keep_daily,
// keep_weekly, keep_monthly. Only keep_last is wired today.
type Retention struct {
	KeepLast int `yaml:"keep_last"`
}

const header = `# Auto-generated by tools/lib/assemble-crons — DO NOT EDIT BY HAND.
# Sources: iac/cron.yaml, services/*/cron.yaml, services/*/backups.yaml.
# Re-run tools/apply.sh to regenerate.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

func main() {
	repo := "."
	if len(os.Args) > 1 {
		repo = os.Args[1]
	}
	root, err := filepath.Abs(repo)
	if err != nil {
		fatalf("resolve repo root: %v", err)
	}

	entries := loadCronEntries(root)
	entries = append(entries, loadBackupEntries(root)...)

	seen := map[string]string{} // name -> source path (for uniqueness check)
	var out strings.Builder
	out.WriteString(header)

	for _, e := range entries {
		if e.Name == "" || e.Schedule == "" || e.Command == "" || e.Log == "" {
			fatalf("%s: entry missing required field(s) (name/schedule/command/log): %+v", e.source, e)
		}
		if prev, ok := seen[e.Name]; ok {
			fatalf("duplicate cron name %q in %s (also in %s)", e.Name, e.source, prev)
		}
		seen[e.Name] = e.source

		fmt.Fprintf(&out, "\n# %s — %s\n", e.source, e.Name)
		if desc := strings.TrimSpace(e.Description); desc != "" {
			for _, line := range strings.Split(desc, "\n") {
				if line != "" {
					fmt.Fprintf(&out, "#   %s\n", line)
				}
			}
		}
		user := e.User
		if user == "" {
			user = "root"
		}
		fmt.Fprintf(&out, "%s %s %s >> %s 2>&1\n",
			e.Schedule, user, resolveCommand(e.Command), e.Log)
	}

	if _, err := os.Stdout.WriteString(out.String()); err != nil {
		fatalf("write stdout: %v", err)
	}
}

// loadCronEntries reads iac/cron.yaml + services/*/cron.yaml in stable order.
func loadCronEntries(root string) []Entry {
	var files []string
	iacCron := filepath.Join(root, "iac", "cron.yaml")
	if _, err := os.Stat(iacCron); err == nil {
		files = append(files, iacCron)
	}
	svcFiles, err := filepath.Glob(filepath.Join(root, "services", "*", "cron.yaml"))
	if err != nil {
		fatalf("glob services/*/cron.yaml: %v", err)
	}
	sort.Strings(svcFiles)
	files = append(files, svcFiles...)

	var out []Entry
	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			fatalf("read %s: %v", rel, err)
		}
		var entries []Entry
		if err := yaml.Unmarshal(data, &entries); err != nil {
			fatalf("parse %s: %v", rel, err)
		}
		for i := range entries {
			entries[i].source = rel
		}
		out = append(out, entries...)
	}
	return out
}

// loadBackupEntries reads services/*/backups.yaml and synthesizes one cron
// Entry per backup spec, invoking tools/lib/backups/run.sh with flags built
// from the spec. The output log path follows /var/log/backup-<name>.log.
func loadBackupEntries(root string) []Entry {
	files, err := filepath.Glob(filepath.Join(root, "services", "*", "backups.yaml"))
	if err != nil {
		fatalf("glob services/*/backups.yaml: %v", err)
	}
	sort.Strings(files)

	var out []Entry
	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			fatalf("read %s: %v", rel, err)
		}
		var backups []Backup
		if err := yaml.Unmarshal(data, &backups); err != nil {
			fatalf("parse %s: %v", rel, err)
		}
		for _, b := range backups {
			out = append(out, backupToEntry(b, rel))
		}
	}
	return out
}

// backupToEntry validates a Backup spec and converts it into a cron Entry
// whose Command invokes tools/lib/backups/run.sh with the right flags.
func backupToEntry(b Backup, source string) Entry {
	required := map[string]string{
		"name":     b.Name,
		"engine":   b.Engine,
		"host":     b.Host,
		"dest_dir": b.DestDir,
		"schedule": b.Schedule,
	}
	for k, v := range required {
		if v == "" {
			fatalf("%s: backup entry missing required field %q: %+v", source, k, b)
		}
	}
	if b.Retention.KeepLast <= 0 {
		fatalf("%s: backup entry %q: retention.keep_last must be a positive integer (got %d)",
			source, b.Name, b.Retention.KeepLast)
	}

	args := []string{
		"--engine", b.Engine,
		"--name", b.Name,
		"--host", b.Host,
		"--dest-dir", b.DestDir,
		"--retention-keep-last", fmt.Sprintf("%d", b.Retention.KeepLast),
	}

	switch b.Engine {
	case "postgres":
		for k, v := range map[string]string{
			"container": b.Container,
			"user":      b.User,
			"database":  b.Database,
		} {
			if v == "" {
				fatalf("%s: backup %q (engine=postgres) missing required field %q",
					source, b.Name, k)
			}
		}
		args = append(args,
			"--container", b.Container,
			"--user", b.User,
			"--database", b.Database,
		)
	case "sqlite":
		if b.Src == "" {
			fatalf("%s: backup %q (engine=sqlite) missing required field %q",
				source, b.Name, "src")
		}
		args = append(args, "--src", b.Src)
	default:
		fatalf("%s: backup %q has unknown engine %q (supported: postgres, sqlite)",
			source, b.Name, b.Engine)
	}

	return Entry{
		Name:     "backup-" + b.Name,
		Schedule: b.Schedule,
		Command:  "tools/lib/backups/run.sh " + strings.Join(args, " "),
		Log:      "/var/log/backup-" + b.Name + ".log",
		Description: fmt.Sprintf("Declarative backup (engine=%s, host=%s, retention.keep_last=%d). Spec in %s.",
			b.Engine, b.Host, b.Retention.KeepLast, source),
		source: source,
	}
}

// resolveCommand rewrites a repo-relative path to its on-host absolute path
// (the ops LXC clones the repo at /root/homelab-iac). Absolute paths pass through.
// The path component may be followed by flags/args separated by spaces.
func resolveCommand(cmd string) string {
	if strings.HasPrefix(cmd, "/") {
		return cmd
	}
	// Split first whitespace: rewrite only the executable path.
	if i := strings.IndexByte(cmd, ' '); i >= 0 {
		return "/root/homelab-iac/" + cmd[:i] + cmd[i:]
	}
	return "/root/homelab-iac/" + cmd
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "assemble-crons: "+format+"\n", args...)
	os.Exit(1)
}
