# Generate ED25519 keypair for Coolify to use when SSH'ing into runners
resource "tls_private_key" "coolify_runner_key" {
  algorithm = "ED25519"
}

# Push the public key onto each runner LXC
resource "terraform_data" "push_coolify_key_runner_01" {
  triggers_replace = [tls_private_key.coolify_runner_key.public_key_openssh]

  provisioner "local-exec" {
    command = <<-EOC
      KEY=$(echo '${trimspace(tls_private_key.coolify_runner_key.public_key_openssh)}')
      ssh -o StrictHostKeyChecking=accept-new root@192.168.50.210 \
        "grep -qxF \"$KEY\" /root/.ssh/authorized_keys || echo \"$KEY\" >> /root/.ssh/authorized_keys"
    EOC
  }
}

# Create the Coolify private_key via API directly (sierrajc provider has bug #95
# with sensitive attribute roundtrip; bypass by calling API ourselves).
# Output of local-exec is captured into output attribute.
resource "terraform_data" "coolify_private_key" {
  triggers_replace = [tls_private_key.coolify_runner_key.private_key_pem]

  input = {
    private_key = tls_private_key.coolify_runner_key.private_key_pem
    api_token   = local.coolify_api_token
  }

  provisioner "local-exec" {
    command = <<-EOC
      response=$(curl -fsS -X POST \
        -H "Authorization: Bearer ${self.input.api_token}" \
        -H "Content-Type: application/json" \
        --data @- \
        http://192.168.50.200:8000/api/v1/security/keys <<JSON
{"name":"tofu-runner-key","description":"ED25519 generated by tofu","private_key":${jsonencode(self.input.private_key)}}
JSON
      )
      echo "$response" | tee /tmp/coolify_priv_key_response.json
    EOC
  }
}

# Parse the UUID from the response file (written by the provisioner above)
data "external" "coolify_private_key_uuid" {
  depends_on  = [terraform_data.coolify_private_key]
  program     = ["sh", "-c", "cat /tmp/coolify_priv_key_response.json | jq -c '{uuid: .uuid}'"]
}

# Register coolify-runner-01 as a server via API
resource "terraform_data" "coolify_server_runner_01" {
  triggers_replace = [
    data.external.coolify_private_key_uuid.result.uuid,
    "192.168.50.210", # ip
  ]

  input = {
    api_token        = local.coolify_api_token
    private_key_uuid = data.external.coolify_private_key_uuid.result.uuid
  }

  depends_on = [terraform_data.push_coolify_key_runner_01]

  provisioner "local-exec" {
    command = <<-EOC
      curl -fsS -X POST \
        -H "Authorization: Bearer ${self.input.api_token}" \
        -H "Content-Type: application/json" \
        --data @- \
        http://192.168.50.200:8000/api/v1/servers <<JSON
{"name":"coolify-runner-01","description":"LXC 210 on Beelink (pve03 future). coolify;runtime.","ip":"192.168.50.210","port":22,"user":"root","private_key_uuid":"${self.input.private_key_uuid}","instant_validate":true}
JSON
    EOC
  }
}
