# Generate ED25519 keypair for Coolify to use when SSH'ing into runners
resource "tls_private_key" "coolify_runner_key" {
  algorithm = "ED25519"
}

# Push the public key onto each runner LXC over SSH
resource "terraform_data" "push_pubkey_runner_01" {
  triggers_replace = [tls_private_key.coolify_runner_key.public_key_openssh]

  provisioner "local-exec" {
    command = <<-EOC
      KEY=$(echo '${trimspace(tls_private_key.coolify_runner_key.public_key_openssh)}')
      ssh -o StrictHostKeyChecking=accept-new root@${local.ips.coolify_runner_01} \
        "grep -qxF \"$KEY\" /root/.ssh/authorized_keys || echo \"$KEY\" >> /root/.ssh/authorized_keys"
    EOC
  }
}

# Create the Coolify private_key + register the server in one provisioner.
# We bypass the sierrajc provider (bug #95 with sensitive-attr roundtrip)
# AND avoid the data.external pattern (file-on-disk doesn't survive ops LXC
# rebuilds). State only tracks whether this was done; UUIDs live only in
# Coolify. To force re-registration, change a trigger.
resource "terraform_data" "coolify_runner_01" {
  triggers_replace = [
    tls_private_key.coolify_runner_key.private_key_pem,
    local.ips.coolify_runner_01,
  ]

  input = {
    api_token = local.coolify_api_token
    pem       = tls_private_key.coolify_runner_key.private_key_pem
  }

  depends_on = [terraform_data.push_pubkey_runner_01]

  provisioner "local-exec" {
    command = <<-EOC
      set -e

      # 1. Create the Coolify private_key resource
      KEY_BODY=$(jq -nc --arg pem "${self.input.pem}" '{
        name: "tofu-runner-key",
        description: "ED25519 generated by tofu",
        private_key: $pem
      }')
      KEY_RESP=$(curl -fsS -X POST \
        -H "Authorization: Bearer ${self.input.api_token}" \
        -H "Content-Type: application/json" \
        --data "$KEY_BODY" \
        ${local.coolify_api_url}/api/v1/security/keys)
      KEY_UUID=$(echo "$KEY_RESP" | jq -r .uuid)
      [ -n "$KEY_UUID" ] && [ "$KEY_UUID" != "null" ] || { echo "ERROR: failed to create key: $KEY_RESP" >&2; exit 1; }
      echo "==> created Coolify private_key uuid=$KEY_UUID"

      # 2. Register coolify-runner-01 as a server
      SRV_BODY=$(jq -nc --arg pk "$KEY_UUID" '{
        name: "coolify-runner-01",
        description: "LXC 210. coolify;runtime.",
        ip: local.ips.coolify_runner_01,
        port: 22,
        user: "root",
        private_key_uuid: $pk,
        instant_validate: true
      }')
      SRV_RESP=$(curl -fsS -X POST \
        -H "Authorization: Bearer ${self.input.api_token}" \
        -H "Content-Type: application/json" \
        --data "$SRV_BODY" \
        ${local.coolify_api_url}/api/v1/servers)
      SRV_UUID=$(echo "$SRV_RESP" | jq -r .uuid)
      [ -n "$SRV_UUID" ] && [ "$SRV_UUID" != "null" ] || { echo "ERROR: failed to create server: $SRV_RESP" >&2; exit 1; }
      echo "==> registered server uuid=$SRV_UUID"
    EOC
  }
}
